components:
  parameters:
    idphint:
      name: idphint
      in: query
      schema:
        type: string

      description: |-
        idphint=https%3A%2F%2Fspid.idp.it
      example: idphint=https%3A%2F%2Fspid.idp.it
  responses:
    Attributes:
      description: |
        A successful response returing attributes in
        different formats.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Attribute'
        application/jwt:
          schema:
            $ref: '#/components/schemas/Attribute'

    403MissingUserConsent:
      description: |
        Se una chiamata all'API per la richiesta di attributi qualificati
         non può essere soddisfatta perché sprovvista della prova di
          avvenuto assenso dell’utente, l’AA DEVE ritornare una risposta
          con codice di stato HTTP 403 Forbidden
          e un contenuto di tipo json con l’indicazione descrittiva
          "Authorization required"
          all’interno dell’attributo error_description.
      headers: {}  # TODO
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MissingUserConsent'
  securitySchemes:
        UserConsent:
          type: openIdConnect
          openIdConnectUrl: https://aa.it/.well-known/...
          description: |-
            Questa sezione esplicita il riferimento all'URL di configurazione
            di OIDC relativo al provider. Deve contenere le informazioni indicate in:
            https://openid.net/specs/openid-connect-discovery-1_0.html
        "SPID Attribute Authority Security Scheme": {
          bearerFormat: "JWT",
          description: "JWT Token Authentication Scheme",
          scheme: "bearer",
          type: "http"
        }
  schemas:
    MissingUserConsent:
      $ref: 'https://teamdigitale.github.io/openapi/master/definitions.yaml#/components/schemas/Problem'
    Attribute:
      type: object
      additionalProperties: false
      required:
        - attribute
      properties:
        attribute:
          type: string
          example: ciao
    TokenExchangeResponse:
      type: object
      additionalProperties: false
      required:
        - access_token
        - expires_in
        - issued_token_type
        - token_type
      properties:
        access_token:
          description: |-
            Il contenuto dell'Access Token
          type: string
          format: jwt
          example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
        expires_in:
          type: integer
          example: 3600
          description: tempo di validità del token in secondi.
        issued_token_type:
          description: |-
            Il tipo di token generato.
          type: string
          enum:
          - urn:ietf:params:oauth:token-type:access_token
        token_type:
          description: |-
            Il tipo di token che è stato rilasciato. L'AS
            DEVE supportare almeno il tipo Bearer ma
            può supportare anche altri tipi di token compatibili
            con quelli supportati dalle AA.
          type: string
          example: Bearer
          enum:
          - Bearer
          - DPoP
    TokenExchangeRequest:
      additionalProperties: false
      type: object
      required:
      - grant_type
      - client_assertion
      - client_assertion_type
      - requested_token_type
      - subject_token
      - scope
      - subject_token_type
      properties:
        grant_type:
          type: string
          description: |-
            Il tipo di grant richiesta.
          enum:
            - urn:ietf:params:oauth:grant-type:token-exchange
        scope:
          type: string
          example: "read:qualifica"
        client_assertion:
          description: |-
            JWT Token che identifica il client firmato con la chiave
            pubblica del RP, eventualmente associata ad un certificato.
            [RFC7523#section-2.2].
          type: string
          format: jwt
          example: eyJhbGciOiJIUzI1NiIs…
          externalDocs:
            url: https://datatracker.ietf.org/doc/html/rfc7523#section-2.2
        client_assertion_type:
          type: string
          description: |-
            Una client assertion descritta in [RFC7523#section-2.2].
          enum:
          - urn:ietf:params:oauth:client-assertion-type:jwt-bearer
          externalDocs:
            url: https://datatracker.ietf.org/doc/html/rfc7523#section-2.2
        requested_token_type:
          description: |-
            Il tipo di token richiesto.
          type: string
          format: urn
          enum:
          - urn:ietf:params:oauth:token-type:access_token
        subject_token:
          description: |-
            Il Grant Token ottenuto precedentemente dall'IdP e
            spendibile presso la AA.
          type: string
          format: jwt
          example: eyJhbGciOiJS...
        subject_token_type:
          description: |-
            Il tipo di subject token.
          type: string
          format: url
          enum:
          - https://spid.gov.it/attribute-authority/grant-token
        resource:
          description: |-
            URL assoluta corrispondente all’endpoint presso l’AA che permette di recuperare
            l’attributo qualificato e per il quale si vuole ottenere l’access_token.
            È possibile utilizzare un array di resource per indicare
            che l’access_token emesso è destinato a essere utilizzato presso
            diverse risorse.
          type: string
          format: url
          example: https://rs.aa1.it/attributes
          externalDocs:
            url: https://datatracker.ietf.org/doc/html/rfc8693/#section-2.1

    JWTReplaySafe:
      required:
        - iat
        - exp
        - nbf
        - jti
      properties: &JWTReplaySafe
        iat:
          type: integer
          format: int64
          description: |-
            Timestamp di emissione del token, espresso in
            UNIX Timestamp.
          example: 1546300800
          externalDocs:
            url: https://tools.ietf.org/html/rfc7519#section-4.1.6
        exp:
          type: integer
          format: int64
          description: |-
            Timestamp di scadenza del token, espresso in
            UNIX Timestamp.
          externalDocs:
            url: https://tools.ietf.org/html/rfc7519#section-4.1.4
        nbf:
          type: integer
          format: int64
          description: |-
            Timestamp di inizio validità del token,
            espresso in UNIX Timestamp.
          externalDocs:
            url: https://tools.ietf.org/html/rfc7519#section-4.1.5
        jti:
          type: string
          format: uuid
          example: 2b71281c-cbcc-4ba9-9034-50b588161bd1
          description: |-
            Identificativo univoco del token.
          externalDocs:
            url: https://tools.ietf.org/html/rfc7519#section-4.1.7
    GrantTokenHeader:
      required:
      - typ
      properties:
        typ:
          type: string
          description: |-
            Identifica il tipo di token che si sta inviando.
          enum:
          - aa-grant+jwt
    GrantTokenPayload:
      required:
      - iss
      - sub
      - aud
      - iat
      - exp
      # altri valori.
      - act
      - sid
      - acr
      properties:
        <<: *JWTReplaySafe
        aud:
          type: string
          description: |-
            Identificativo della AA cui è destinato il token corrispondente,
            corrispondente al claim `iss` contenuto all’interno
            dei metadata della AA.
          externalDocs:
            url: https://www.rfc-editor.org/rfc/rfc7519.html#section-4.1.3
        sid:
          type: string
          description: |-
            ResponseID SAML2 (con prefisso “saml:” )
             o jti dell’ID Token OIDC (con prefisso “oidc:”),
             per collegare il Grant Token all’autenticazione.
          externalDocs:
            url: https://openid.net/specs/openid-connect-frontchannel-1_0.html
        acr:
          type: string
          description: |-
            Identifica il livello di autenticazione SPID.
        iss:
          type: string
          format: url
          description: |-
            Identificativo dell’IdP che ha emesso il token.
        sub:
          type: string
          format: url
          description: |-
            Identificativo univoco dell’utente di tipo public. il valore è da interpretare in relazione all’attributo di lookup (aa-lookup-attribute) dichiarato nel documento OpenAPI.
        act:
          description: |-
            Oggetto JSON che contiene il claim sub valorizzato
            con l’identificativo del SP (entityID) / RP (client_id)
              al quale viene restituito il GrantToken.
              Esempio:
              ```"act": { "sub": "https://rp.spid.gov.it" }```
              .
          type: object
          required:
            - sub
          properties:
            sub:
              type: string
              format: url
              description: |-
                Identificativo univoco dell’utente di tipo public. il valore è da interpretare in relazione all’attributo di lookup (aa-lookup-attribute) dichiarato nel documento OpenAPI.
    Token:
      type: string
      format: jwt
    JWTPayload: &JWTPayload
      required:
      - iss
      - sub
      - jti
      - iat
      - exp
      - nbf
      properties:
        <<: *JWTReplaySafe
        iss:
          description: URL che identifica univocamente l’emittente del  trust mark (SGD-AA. o SA abilitati)
          type: string
          format: url
          maxLength: 4096
          minLength: 12
        sub:
          description: URL che identifica univocamente l’ente/organizzazione che intende aderire al SGD
          type: string
          format: url
          maxLength: 4096
          minLength: 12

    JoseHeader: &JoseHeaderBase
      required:
      - typ
      - alg
      - kid
      properties:
        typ:
          type: string
          description: |-
           Tipologia del Token, come normato dalle LG SPID OIDC e successivi avvisi,
           se non specializzata assume il valore di “JWT”.
        alg:
          type: string
          description: |-
            Identifica l’algoritmo di cifratura utilizzato per firmare il JWT.
            Come normato dalle LG SPID OIDC e successivi avvisi.
        kid:
          type: string
          description: |-
            Come normato dalle LG SPID OIDC e successivi avvisi.
    All:
      anyOf:
      - $ref: '#/components/schemas/OIDCMetadataPrivate'
      - $ref: '#/components/schemas/OIDCMetadataProtected'
      - $ref: '#/components/schemas/XSPID'
      - $ref: '#/components/schemas/XSPIDOperation'
      - $ref: '#/components/schemas/GrantTokenPayload'
    OIDCMetadataProtected:
      type: object
      description: |-
        Per il flusso protected, non dev'esserci l'authorization endpoint
        perché l'utente non deve richiedere un authorization grant.
      required:
        - token_endpoint
    OIDCMetadataPrivate:
      type: object
      description: |-
        Per il flusso Private, servono authorization_endpoint e token_endpoint
        perché l'autenticazione avviene su base utente.
      required:
        - authorization_endpoint
        - token_endpoint
    XSPID:
      required:
      - aa-home
      - aa-lookup-attribute
      - aa-registry
      - aa-required-attributes
      - aa-version
      properties:
        aa-version:
          type: string
          format: url
          description: |-
            OBBLIGATORIO. Deve contenere il valore 1.0.0 quale riferimento alla versione delle linee guida SPID per le AA cui l’API fa riferimento. Tale valore non è da confondere con il valore nel campo openapi che specifica la versione OpenAPI, né con il valore nel campo version dell’oggetto info, che invece specifica la versione del documento.
        aa-home:
          type: string
          format: url
          description: |-
            OBBLIGATORIO. URI presso l’AA dove è esposto il presente documento OpenAPI
        aa-lookup-attribute:
          type: string
          format: url
          description: |-
            OBBLIGATORIO. Stringa corrispondente all’attributo SPID utilizzato dalla AA come chiave di ricerca per l’utente. DEVE essere presente tra gli attributi indicati in in aa-required-attributes.
        aa-registry:
          type: string
          format: url
          description: |-
            OBBLIGATORIO. URI presso il registro SPID delle AA dove è esposto il presente documento OpenAPI
        aa-required-attributes:
          description: |-
            OBBLIGATORIO. Array di stringhe corrispondenti agli attributi SPID necessari alla AA per le proprie finalità. Es.: [‘fiscalNumber’, ‘email’]
          type: array
          minItems: 0
          maxItems: 10
          items:
            type: string
            description: |-
              Lista degli attributi richiesti dall'AA

    XSPIDOperation:
      type: object
      description: |-
        Questa sezione contiene le informazioni relative all'operazione.
      required:
      - consentRequired
      - consentType
      - spidLevel
      - offlineAccess
      - offlineAccessDurationMax
      additionalProperties: false
      properties:
        consentType:
          description: |-
            Tipo di consenso richiesto.
          type: array
          minItems: 0
          maxItems: 10
          uniqueItems: true
          items:
            type: string
            enum:
              - AA
              - SP

  examples:
    TokenExample:
      description: |-
        OIDC Metadata che viene pubblicato in JSON.
      value:
        version: '3.0'
        introspection_endpoint: https://as.aa.it/introspection
        issuer: https://as.aa.it
        jwks_uri: https://as.aa.it/static/jwks.json
        logo_uri: https://as.aa.it/static/logo.svg
        organization_name: Example Attribute Authority
        authorization_endpoint: https://as.aa.it/authorization
        end_session_endpoint: https://as.aa.it/session
        token_endpoint: https://as.aa.it/token
        acr_values_supported:
        - https://www.spid.gov.it/SpidL1
        - https://www.spid.gov.it/SpidL2
        claim_types_supported:
        - normal
        - aggregated
        - distributed
        claims_parameter_supported: true
        claims_supported:
        - iss
        - zoneinfo
        - updated_at
        - sub
        client_authn_method:
        - bearer_header
        grant_types_supported:
        - authorization_code
        - urn:ietf:params:oauth:grant-type:jwt-bearer
        - refresh_token
        id_token_encryption_alg_values_supported:
        - RSA-OAEP
        - RSA-OAEP-256
        id_token_encryption_enc_values_supported:
        - A128GCM
        - A192GCM
        - A256GCM
        id_token_signing_alg_values_supported:
        - RS256
        request_object_encryption_alg_values_supported:
        - RSA-OAEP
        - RSA-OAEP-256
        request_object_encryption_enc_values_supported:
        - A128GCM
        - A192GCM
        - A256GCM
        request_object_signing_alg_values_supported:
        - RS256
        response_modes_supported:
        - query
        - fragment
        - form_post
        response_types_supported:
        - code
        scopes_supported:
        - offline_access
        - openid
        - read:qualifica
        subject_types_supported:
        - public
        - pairwise
        token_endpoint_auth_methods_supported:
        - private_key_jwt
        token_endpoint_auth_signing_alg_values_supported:
        - RS256
        userinfo_signing_alg_values_supported:
        - RS256
openapi: 3.0.2
info:
  title: Esempio di Attribute Authority
  version: 1.1.0
  description: |-
    Descrizione delle informazioni restituite dall'Attribute Authority.
  termsOfService: https://api.aa.it/tos
  contact:
    name: Contatto di riferimento
    url: https://www.aa.it
  x-spid:
    aa-version: 1.0.0
    aa-home: https://api.aa.it/v1/openapi.json
    aa-registry: https://registry.spid.gov.it/metadata/aa/ente.json
    aa-lookup-attribute: fiscalNumber
    aa-required-attributes:
    - fiscalNumber
    - email
servers:
- url: https://api.aa.it/api/v1
paths:
  /attributo-a:
    get:
      operationId: mostra_attributo_a
      summary: Mostra l'attributo A
      description: |-
        Questa funzione restituisce l'attributo A.
      tags:
      - protected
      - modi
      parameters:
      - name: taxCode
        in: query
        description: Codice fiscale dell'utente
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: |-
            Attributo A restituito con successo.
  /qualifica:
    get:
      operationId: mostra_qualifica
      summary: Mostra un attributo qualificato.
      # Autenticazione di tipo UserConsent
      security:
        - UserConsent: [ 'read:qualifica']
      x-spid-operation:
        consentRequired: true
        spidLevel: L1
        offlineAccessExpiresIn: 864000
      responses:
        "200":
          description: |-
            Attributo qualificato restituito con successo."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Attribute"
            application/jwt:
              schema:
               type: string
               pattern: ^[a-zA-Z\_\-0-9]+\.[a-zA-Z\_\-0-9]+\.[a-zA-Z\_\-0-9]+$
               description: |-
                  Un oggetto il cui payload è definito in
                  #/components/schemas/QualificaJWTPayload.
                  Indicare se la codifica è JWE o JWS.

  /as/token:
    post:
      security:
        - {}  # Autenticazione basata sul contenuto della request.

      operationId: as_token
      summary: Richiesta di token di autenticazione
      description: |-
        Questa funzione restituisce un Access Token.
      tags:
      - oauth2
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/TokenExchangeRequest"
      responses:
        "200":
          description: |-
            Token di autenticazione restituito con successo.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
  /status: {}

tags:
- description: Accesso pubblico
  externalDocs:
    description: Linee Guida Attribute Authority SPID
    url: https://www.agid.gov.it/...
  name: public
- description: Accesso riservato a SP convenzionati
  externalDocs:
    description: Linee Guida Attribute Authority SPID
    url: https://www.agid.gov.it/...
  name: protected
- description: |-
    Accesso previa acquisizione dell'assenso dell'utente da
    parte dell'AA
  externalDocs:
    description: Linee Guida Attribute Authority SPID
    url: https://www.agid.gov.it/...
  name: private
- name: protected-convenzione-caf
  description: Accesso pubblico per CAF convenzionati
  externalDocs:
    description: Convenzione che regola l’accesso ai dati per i CAF
    url: "https://foo.bar"
